### ISSUE TITLE
Error in .hasNoSharing() : could not find function ".hasNoSharing"

### ISSUE THREAD

**Issue by mquikscr** [btskinner/duawranglr#9]
Hi btskinner,

I am running into an error with deidenitfying the data.  Any help would be much appreciated.  Here is the code I have been using:

```r
library(duawranglr)

## get crosswalk and admin data files
dua_cw_file <- system.file('extdata', 'dua_cw.csv', package = 'duawranglr')
admin_file <- system.file('extdata', 'admin_data.csv', package = 'duawranglr')

## set the DUA crosswalk
set_dua_cw(dua_cw_file)

set_dua_level('level_ii', deidentify_required = TRUE, id_column = 'CCCCO_Assigned')

## compare level II and III restrictions
see_dua_options(level = c('level_ii', 'level_iii'))

## deidentify data
Award_DB_14_20_tableau <- deid_dua(Award_DB_14_20_work, id_col = 'CCCCO_Assigned', new_id_name = 'id', write_crosswalk = TRUE, id_length = 20)
```
The last ## step is where i'm running into the error, do you have any suggestions?

best,
mark

**Comment by btskinner** [comment]
Hi @mquikscr, I get a slightly different error, but I think the root cause might be the same. Is this the exact code you are running? If so, I think your problem is that you are mixing lines from the example vignette with your own code. These two lines

```r
## get crosswalk and admin data files
dua_cw_file <- system.file('extdata', 'dua_cw.csv', package = 'duawranglr')
admin_file <- system.file('extdata', 'admin_data.csv', package = 'duawranglr')
```

are just illustrative examples from the vignette. You need to read in your own data set (the one you want to deidentify) and your own crosswalk (the one that has the restricted variables in columns by restriction level).

**Comment by btskinner** [comment]
Closing issue since it appears stale.
